### ISSUE TITLE
Drag-and-drop does not work out of the box

### ISSUE THREAD

**Issue by shubhamsinghshubham777** [canopas/compose-recyclerview#13]
First of all, I want to thank you for this nice wrapper around RecyclerView 👏🏻 

Secondly, as a new user, the README/documentation of this repository was not very clear in informing me that for drag-and-drop to work, I need to pass in an object of `ComposeRecyclerViewAdapter.ItemTypeBuilder`. I had to figure it out by trial and error.

Therefore, to make it easier for future users to get started easily, I'd request you to either mention the fact above, or better yet, instead of using `null` as the default value for the `itemTypeBuilder` param in `ComposeRecyclerView`, give it a default non-null value that allows drag-and-drop by default.

For example:
```kotlin
private val DefaultItemTypeBuilder = object : ComposeRecyclerViewAdapter.ItemTypeBuilder {
    override fun getItemType(position: Int): Int = 0
}

// Rest of the code
// Mention that in order to remove drag-and-drop, users would need to pass `null` into this param
itemTypeBuilder: ComposeRecyclerViewAdapter.ItemTypeBuilder = DefaultItemTypeBuilder,
// Rest of the code
```

**Comment by cp-megh-l** [comment]
Thank you for your feedback and for using our library!

I apologize for the confusion regarding the drag-and-drop functionality. By default, the `itemTypeBuilder` parameter is set to null, which means drag-and-drop will not be enabled unless a non-null `ComposeRecyclerViewAdapter.ItemTypeBuilder` is provided.

To address this issue, I will update the documentation to clearly specify that in order to enable drag-and-drop functionality, passing a non-null `itemTypeBuilder` is mandatory. This will help future users understand this requirement more easily.

Thank you again for pointing this out. If you have any more suggestions or encounter other issues, please feel free to let us know.
